### ISSUE TITLE
Please add a COPYING or LICENSE file stating the usage term

### ISSUE THREAD

**Issue by mih** [rproepp/spykeviewer#1]
no more text. ;-)

**Comment by yarikoptic** [comment]
+1 ;-)

**Comment by yarikoptic** [comment]
as for the license choice might make more sense to stay in line with NEO itself which is under BSD-2 license

**Comment by rproepp** [comment]
BSD license added as of 0.1.1

**Comment by yarikoptic** [comment]
awesome!  note that you can close issues within commit messages, e.g. just add "(Closes gh-1)" to it while committing
